############################################################
#
# 开发环境配置
#
############################################################
server:
  # 应用的端口
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat连接数满后的排队数 默认是100
    accept-count: 1000
    threads:
      # tomcat 线程池最大线程数 默认是200
      max: 800
      # tomcat 线程池初始化时线程数 默认是10
      min-spare: 100

spring:
  profiles:
    active: prod

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  # 所有的POJO类所在的包路径
  type-aliases-package: com.markus.project.**.domain
  # mapper文件加载路径
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 全局配置文件路径
  config-location: classpath:/mybatis/mybatis-config.xml

############################################################
#
# 配置demo
#
############################################################
people:
  name: markus
  sex: male
  age: 24